name: simak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  calendar_appbar: ^0.0.6
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.6
  faker: 2.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  get: 4.6.6
  image_picker: 1.1.1
  material: ^1.0.0+2

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_simak.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/images/
    - assets/icon/
  uses-material-design: true
