name: simak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  faker: 2.1.0
  image_picker: 1.1.1
  flutter_launcher_icons: 0.13.1
  calendar_appbar: 0.0.6
  google_fonts: ^6.2.0
  intl: ^0.17.0
  file_picker: ^4.0.0
  sp_util: 2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/icon/icon_simak.png
  ios: true
  min_sdk_android: 21

flutter:
  assets:
    - assets/image/
    - assets/icon/
  uses-material-design: true
